name: Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: Install Avado SDK
        run: |
          npm i -g git+https://github.com/AvadoDServer/AVADOSDK.git
      - name: git checkout
        run: |
          git clone github.repositoryUrl .
          # git fetch origin pull/${payload.pull_request.number}/head:pr
          git fetch origin ${{github.ref}}
          git checkout pr
      - name: Alias "docker compose" as docker-compose for avadosdk
        run: |
          sudo sh -c 'echo "docker compose --compatibility \"\$@\"" > /bin/docker-compose'
          sudo chmod +x /bin/docker-compose
      - name: Build package
        run: avadosdk build --provider http://80.208.229.228:5001
      - name: Create diff file
        run: sudo apt-get install -y jq
      - name: create diff-file for release workflow
        run: |
          git add --force --intent-to-add releases.json
          git diff >> ${GITHUB_SHA}.diff
      - name: Upload diff file
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: ${{github.sha}}.diff
          path: ${{github.sha}}.diff
